(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default bold shadow italic underline bold bold-italic bold])
 '(ansi-color-names-vector
   ["#1D252C" "#D95468" "#8BD49C" "#EBBF83" "#5EC4FF" "#E27E8D" "#70E1E8" "#A0B3C5"])
 '(bm-repository-file "~/.emacs.d/config-file/bm-repository")
 '(bookmark-default-file "~/.emacs.d/config-file/bookmarks")
 '(custom-safe-themes
   '("9c27124b3a653d43b3ffa088cd092c34f3f82296cf0d5d4f719c0c0817e1afa6" "e838d6375a73fda607820c65eb3ea1f9336be7bd9a5528c9161e10c4aa663b5b" "274fa62b00d732d093fc3f120aca1b31a6bb484492f31081c1814a858e25c72e" "a24c5b3c12d147da6cef80938dca1223b7c7f70f2f382b26308eba014dc4833a" "b0fd04a1b4b614840073a82a53e88fe2abc3d731462d6fde4e541807825af342" "fa2b58bb98b62c3b8cf3b6f02f058ef7827a8e497125de0254f56e373abee088" "732b807b0543855541743429c9979ebfb363e27ec91e82f463c91e68c772f6e3" "10461a3c8ca61c52dfbbdedd974319b7f7fd720b091996481c8fb1dded6c6116" "cb477d192ee6456dc2eb5ca5a0b7bd16bdb26514be8f8512b937291317c7b166" "bffa9739ce0752a37d9b1eee78fc00ba159748f50dc328af4be661484848e476" default))
 '(default-frame-alist
    '((ns-appearance . dark)
      (ns-transparent-titlebar . t)
      (left-fringe . 1)
      (right-fringe . 1)))
 '(eshell-directory-name "~/.emacs.d/config-file/eshell/")
 '(fci-rule-color "#56697A")
 '(git-gutter:added-sign "+")
 '(git-gutter:deleted-sign "-")
 '(git-gutter:lighter " GG")
 '(git-gutter:modified-sign " ")
 '(git-gutter:update-interval 1)
 '(hl-sexp-background-color "#1c1f26")
 '(hl-todo-keyword-faces
   '(("TODO" . "#dc752f")
     ("NEXT" . "#dc752f")
     ("THEM" . "#2d9574")
     ("PROG" . "#3a81c3")
     ("OKAY" . "#3a81c3")
     ("DONT" . "#f2241f")
     ("FAIL" . "#f2241f")
     ("DONE" . "#42ae2c")
     ("NOTE" . "#b1951d")
     ("KLUDGE" . "#b1951d")
     ("HACK" . "#b1951d")
     ("TEMP" . "#b1951d")
     ("FIXME" . "#dc752f")
     ("XXX" . "#dc752f")
     ("XXXX" . "#dc752f")
     ("???" . "#dc752f")))
 '(hyde-images-dir "img")
 '(ido-save-directory-list-file "~/.emacs.d/config-file/ido.last")
 '(jdee-db-active-breakpoint-face-colors (cons "#10151C" "#5EC4FF"))
 '(jdee-db-requested-breakpoint-face-colors (cons "#10151C" "#8BD49C"))
 '(jdee-db-spec-breakpoint-face-colors (cons "#10151C" "#384551"))
 '(objed-cursor-color "#D95468")
 '(org-agenda-files
   '("/Users/kinney/iCloud/org/gtd.org" "/Users/kinney/iCloud/org/inbox.org"))
 '(org-agenda-property-list '("SUMMARY"))
 '(org-bullets-bullet-list nil)
 '(org-capture-bookmark nil)
 '(org-clock-persist-file "~/.emacs.d/config-file/org-clock-save.el")
 '(org-directory "~/iCloud")
 '(org-habit-graph-column 50)
 '(org-habit-preceding-days 7)
 '(org-habit-show-all-today t)
 '(org-habit-show-habits-only-for-today t)
 '(org-icalendar-combined-agenda-file "~/iCloud/org.ics")
 '(org-icalendar-store-UID nil)
 '(org-id-locations-file "~/.emacs.d/config-file/.org-id-locations")
 '(org-jekyll-md-include-yaml-front-matter t)
 '(org-journal-date-format "%A, %d %B %Y" t)
 '(org-journal-dir "~/iCloud/journal/" t)
 '(org-log-done 'time)
 '(org-log-into-drawer t)
 '(org-pomodoro-finished-sound-p t)
 '(org-pomodoro-length 40)
 '(org-pomodoro-long-break-frequency 3)
 '(org-pomodoro-long-break-length 15)
 '(org-pomodoro-long-break-sound-p t)
 '(org-pomodoro-overtime-sound-p nil)
 '(org-pomodoro-play-sounds t)
 '(org-pomodoro-short-break-sound-p t)
 '(package-selected-packages
   '(org-ql general git-gutter bm quelpa-use-package company-prescient ivy-prescient prescient org-analyzer xwidgete diminish jekyll jekyll-mode org-pomodoro google-translate cal-china-x org-super-agenda fasd youdao-dictionary ycmd xterm-color xelb winum window-numbering which-key web-mode web-beautify wanderlust w3m use-package undo-tree sudoku ssass-mode spotlight spinner spacemacs-theme soundcloud smex smartparens shut-up search-web ruby-hash-syntax robe reveal-in-osx-finder restart-emacs python pyenv-mode py-autopep8 proxy-mode project-persist-drawer powerline popwin podcaster pip-requirements pinboard-popular php-mode pfuture paredit pacmacs package-build osx-dictionary org-projectile org-journal org-gcal org-download org-bullets org-agenda-property nyan-mode noflet nodejs-repl neotree navigel multi-term move-text mmm-mode mingus math-symbol-lists material-theme markdown-preview-mode major-mode-hydra magit-popup magit link-hint js2-refactor js-comint ivy-rich ivy-posframe indent-guide impatient-mode image+ iedit idle-org-agenda hungry-delete ht helpful hackernews habitica graphql goto-chg ggtags geiser furl flycheck fancy-battery expand-region exec-path-from-shell esxml enh-ruby-mode emmet-mode elpy elfeed edit-indirect dracula-theme doom-themes doom-modeline django-mode disable-mouse diredfl dashboard dash-docs darkroom counsel-world-clock counsel-projectile counsel-osx-app company-web company-tern company-tabnine company-posframe company-jedi company-c-headers company-box column-enforce-mode calfw-org calfw buffer-move browse-at-remote bongo benchmark-init beacon auto-yasnippet auto-complete anaconda-mode all-the-icons-ivy all-the-icons-dired ace-window ace-popup-menu ace-jump-mode ac-html-bootstrap ac-html-angular 2048-game))
 '(pdf-view-midnight-colors '("#655370" . "#fbf8ef"))
 '(prescient-save-file "/Users/kinney/.emacs.d/config-file/prescient-save.el")
 '(projectile-cache-file "/Users/kinney/.emacs.d/config-file/projectile.cache")
 '(projectile-known-projects-file
   "/Users/kinney/.emacs.d/config-file/projectile-bookmarks.eld")
 '(python-shell-exec-path '("/usr/local/bin/python3"))
 '(recentf-save-file "~/.emacs.d/config-file/recentf")
 '(save-place-file "~/.emacs.d/config-file/places")
 '(semanticdb-default-save-directory "~/.emacs.d/config-file/semanticdb")
 '(smex-save-file "~/.emacs.d/config-file/smex-items")
 '(symon-sparkline-height 11)
 '(symon-sparkline-thickness 2)
 '(symon-sparkline-type 'boxed)
 '(symon-sparkline-width 100)
 '(transient-history-file "~/.emacs.d/config-file/transient/history.el")
 '(transient-levels-file "~/.emacs.d/config-file/transient/levels.el")
 '(transient-values-file "~/.emacs.d/config-file/transient/values.el")
 '(url-configuration-directory "~/.emacs.d/config-file/url/")
 '(url-cookie-file "/Users/kinney/.emacs.d/config-file/url/cookies")
 '(vc-annotate-background "#1D252C")
 '(vc-annotate-color-map
   (list
    (cons 20 "#8BD49C")
    (cons 40 "#abcd93")
    (cons 60 "#cbc68b")
    (cons 80 "#EBBF83")
    (cons 100 "#e5ae6f")
    (cons 120 "#df9e5b")
    (cons 140 "#D98E48")
    (cons 160 "#dc885f")
    (cons 180 "#df8376")
    (cons 200 "#E27E8D")
    (cons 220 "#df7080")
    (cons 240 "#dc6274")
    (cons 260 "#D95468")
    (cons 280 "#b05062")
    (cons 300 "#884c5c")
    (cons 320 "#604856")
    (cons 340 "#56697A")
    (cons 360 "#56697A")))
 '(vc-annotate-very-old-color nil)
 '(w3m-default-save-directory "~/Downloads"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
